on: [push, pull_request]

name: CI

jobs:
  build_and_test:
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['25.2']
        elixir: ['1.14.2']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # build Rust project for test
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build
        working-directory: ./test/wasm_test
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - run: wasm-pack build
        working-directory: ./test/wasm_test

      # build Elixir project
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
